# Docker Compose configuration for RAGFlow with AWS RDS MySQL
# This configuration removes the local MySQL container and uses external RDS

include:
  - ./docker/docker-compose-base.yml

services:
  ragflow:
    # Remove MySQL dependency since we're using external RDS
    depends_on:
      - es01
      - infinity
      - redis
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 80:80
      - 443:443
      - 5678:5678
      - 5679:5679
      - 9382:9382
    volumes:
      - ./docker/ragflow-logs:/ragflow/logs
      - ./docker/nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./docker/nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./history_data_agent:/ragflow/history_data_agent
      - ./docker/service_conf.yaml.template:/ragflow/conf/service_conf.yaml.template
      - ./docker/entrypoint.sh:/ragflow/entrypoint.sh
    env_file: ./docker/ragflow.env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT-}
      - MACOS=${MACOS-}
    networks:
      - ragflow
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Override to remove MySQL service completely
  # The MySQL service from docker-compose-base.yml will be excluded
  mysql:
    profiles:
      - disabled # This effectively disables the MySQL service

networks:
  ragflow:
    driver: bridge
